include:
  - ../venue-and-menu-service/docker-compose.yaml
  - ../user-service/docker-compose.yml
  - ../review-service/docker-compose.yaml
  - ../order-service/docker-compose.yml
  - ../payment-service/docker-compose.yml

networks:
  feedo:
    name: feedo
    driver: bridge