apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../venue-and-menu-service/k8s
  - ../../user-service/k8s
  - ../../review-service/k8s
  - ../../order-service/k8s
  - ../../payment-service/k8s